---
sidebar: sidebar 
permalink: data-analytics/apache-spark-conclusion.html 
keywords: conclusion 
summary: Esta sección resume este documento sobre las soluciones de almacenamiento de NetApp para Apache Spark. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En este documento, analizamos la arquitectura de Apache Spark, los casos de uso de los clientes y la cartera de almacenamiento de NetApp en relación con el big data, el análisis moderno y la inteligencia artificial, el aprendizaje automático y el aprendizaje automático.  En nuestras pruebas de validación de rendimiento basadas en herramientas de evaluación comparativa estándar de la industria y la demanda de los clientes, las soluciones NetApp Spark demostraron un rendimiento superior en relación con los sistemas Hadoop nativos.  Una combinación de los casos de uso de clientes y los resultados de rendimiento presentados en este informe pueden ayudarlo a elegir una solución Spark adecuada para su implementación.
