---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'netapp, solutions, ai, what"s new, updates, change log' 
summary: Registro de cambios recientes en el material complementario de las soluciones de inteligencia artificial de NetApp . 
---
= Novedades en las soluciones de inteligencia artificial de NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Conozca las novedades en soluciones de inteligencia artificial.



== 18 de agosto de 2025

El sitio de NetApp Solutions ahora es ellink:https://docs.netapp.com/us-en/netapp-solutions-family/index.html["Familia de soluciones NetApp"^] , que incluye los siguientes sitios:

* Soluciones de inteligencia artificial de NetApp
* link:https://docs.netapp.com/us-en/netapp-solutions-containers/index.html["Soluciones de contenedores de NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-dataops/index.html["Soluciones de gestión de datos de NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-databases/index.html["Soluciones de bases de datos de NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-cloud/index.html["Soluciones de nube pública e híbrida de NetApp"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-sap/index.html["Soluciones NetApp para SAP"^]
* link:https://docs.netapp.com/us-en/netapp-solutions-virtualization/index.html["Soluciones de virtualización de NetApp"^]




== 3 de diciembre de 2025

Nueva solución:link:software/ai-hybrid-union.html["Implemente capacitación en IA híbrida con Union.ai y NetApp FlexCache"]

Utilice la orquestación de Union.ai con NetApp FlexCache para ejecutar cargas de trabajo de entrenamiento de IA en GPU en la nube mientras mantiene los datos confidenciales en las instalaciones.  FlexCache almacena en caché solo los datos necesarios en la nube para una capacitación híbrida eficiente y segura.
