---
sidebar: sidebar 
permalink: infra/ai-lenovo-train-conclusion.html 
keywords: acknowledgements, additional information 
summary: Esta solución de NetApp y Lenovo es una arquitectura de escalamiento flexible que es ideal para ingresar a la IA empresarial de nivel medio.  El almacenamiento de NetApp ofrece el mismo rendimiento o uno mejor que el almacenamiento SSD local y ofrece los siguientes beneficios a los científicos de datos, ingenieros de datos y tomadores de decisiones de TI. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La solución de NetApp y Lenovo validada aquí es una arquitectura de escalamiento flexible que es ideal para ingresar a la IA empresarial de nivel medio.

El almacenamiento de NetApp ofrece el mismo rendimiento o mejor que el almacenamiento SSD local y ofrece los siguientes beneficios a los científicos de datos, ingenieros de datos y tomadores de decisiones de TI:

* Intercambio de datos sin esfuerzo entre sistemas de IA, análisis y otros sistemas comerciales críticos.  Este intercambio de datos reduce la sobrecarga de infraestructura, mejora el rendimiento y agiliza la gestión de datos en toda la empresa.
* Computación y almacenamiento escalables de forma independiente para minimizar costos y mejorar la utilización de recursos.
* Flujos de trabajo de desarrollo e implementación optimizados mediante instantáneas y clones integrados para espacios de trabajo de usuario instantáneos y que ahorran espacio, control de versiones integrado e implementación automatizada.
* Protección de datos de nivel empresarial para recuperación ante desastres y continuidad del negocio.




== Expresiones de gratitud

* Karthikeyan Nagalingam, ingeniero de marketing técnico, NetApp
* Jarrett Upton, administrador, sistemas de laboratorio de IA, Lenovo




== Dónde encontrar información adicional

Para obtener más información sobre la información descrita en este documento, consulte los siguientes documentos y/o sitios web:

* Página de productos de matrices all-flash de NetApp
+
https://www.netapp.com/us/products/storage-systems/all-flash-array/aff-a-series.aspx["https://www.netapp.com/us/products/storage-systems/all-flash-array/aff-a-series.aspx"^]

* Página de NetApp AFF A400
+
https://docs.netapp.com/us-en/ontap-systems/a400/index.html["https://docs.netapp.com/us-en/ontap-systems/a400/index.html"]

* Página del producto del software de gestión de datos NetApp ONTAP
+
http://www.netapp.com/us/products/data-management-software/ontap.aspx["http://www.netapp.com/us/products/data-management-software/ontap.aspx"^]

* MLPerf
+
https://mlperf.org/["https://mlperf.org"^]

* Prueba de referencia de TensorFlow
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* NVIDIA SMI (nvidia-smi)
+
https://developer.nvidia.com/nvidia-system-management-interface["https://developer.nvidia.com/nvidia-system-management-interface"]


