---
sidebar: sidebar 
permalink: infra/ai-lenovo-edge-conclusion.html 
keywords: acknowledgements, additional information 
summary: La automatización impulsada por IA y la computación de borde son un enfoque líder para ayudar a las organizaciones comerciales a lograr la transformación digital y maximizar la eficiencia y la seguridad operativa.  Con la computación de borde, los datos se procesan mucho más rápido porque no tienen que viajar hacia y desde un centro de datos.  Por lo tanto, se reduce el coste asociado al envío de datos de ida y vuelta a los centros de datos o a la nube. 
---
= Conclusión
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La automatización impulsada por IA y la computación de borde son un enfoque líder para ayudar a las organizaciones comerciales a lograr la transformación digital y maximizar la eficiencia y la seguridad operativa.  Con la computación de borde, los datos se procesan mucho más rápido porque no tienen que viajar hacia y desde un centro de datos.  Por lo tanto, se reduce el coste asociado al envío de datos de ida y vuelta a los centros de datos o a la nube.  Una menor latencia y una mayor velocidad pueden ser beneficiosas cuando las empresas deben tomar decisiones casi en tiempo real utilizando modelos de inferencia de IA implementados en el borde.

Los sistemas de almacenamiento de NetApp ofrecen el mismo rendimiento o uno mejor que el almacenamiento SSD local y ofrecen los siguientes beneficios a científicos de datos, ingenieros de datos, desarrolladores de IA/ML y tomadores de decisiones comerciales o de TI:

* Intercambio de datos sin esfuerzo entre sistemas de IA, análisis y otros sistemas comerciales críticos.  Este intercambio de datos reduce la sobrecarga de infraestructura, mejora el rendimiento y agiliza la gestión de datos en toda la empresa.
* Computación y almacenamiento escalables de forma independiente para minimizar costos y mejorar el uso de recursos.
* Flujos de trabajo de desarrollo e implementación optimizados mediante copias Snapshot y clones integrados para espacios de trabajo de usuario instantáneos y que ahorran espacio, control de versiones integrado e implementación automatizada.
* Protección de datos de nivel empresarial para recuperación ante desastres y continuidad comercial.  La solución de NetApp y Lenovo presentada en este documento es una arquitectura flexible y escalable que es ideal para implementaciones de inferencia de IA de nivel empresarial en el borde.




== Expresiones de gratitud

* JJ  Falkanger, director sénior de soluciones HPC e IA, Lenovo
* Dave Arnette, ingeniero de marketing técnico, NetApp
* Joey Parnell, director técnico de soluciones de IA de la serie E, NetApp
* Cody Harryman, ingeniero de control de calidad, NetApp




== Dónde encontrar información adicional

Para obtener más información sobre la información descrita en este documento, consulte los siguientes documentos y/o sitios web:

* Página de producto de matrices NetApp AFF Serie A
+
https://www.netapp.com/data-storage/aff-a-series/["https://www.netapp.com/data-storage/aff-a-series/"^]

* Software de gestión de datos NetApp ONTAP: biblioteca de información ONTAP 9
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* TR-4727: Introducción a la serie EF de NetApp
+
https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17179-tr4727pdf.pdf"^]

* Hoja de datos del software SANtricity de la serie E de NetApp
+
https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf["https://www.netapp.com/pdf.html?item=/media/19775-ds-3171-66862.pdf"^]

* Almacenamiento persistente de NetApp para contenedores: NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* MLPerf
+
** https://mlcommons.org/en/["https://mlcommons.org/en/"^]
** http://www.image-net.org/["http://www.image-net.org/"^]
** https://mlcommons.org/en/news/mlperf-inference-v11/["https://mlcommons.org/en/news/mlperf-inference-v11/"^]


* Copia y sincronización de NetApp BlueXP
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* Prueba de referencia de TensorFlow
+
https://github.com/tensorflow/benchmarks["https://github.com/tensorflow/benchmarks"^]

* Servidor perimetral Lenovo ThinkSystem SE350
+
https://lenovopress.com/lp1168["https://lenovopress.com/lp1168"^]

* Matriz de almacenamiento flash unificada Lenovo ThinkSystem DM5100F
+
https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array["https://lenovopress.com/lp1365-thinksystem-dm5100f-unified-flash-storage-array"]


