---
sidebar: sidebar 
permalink: software/ai-conf-protopia-addtl.html 
keywords:  
summary:  
---
= Dónde encontrar información adicional y agradecimientos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para obtener más información sobre la información descrita en este documento, consulte los siguientes documentos y/o sitios web:

* Software de gestión de datos NetApp ONTAP : biblioteca de información de ONTAP
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286"^]

* Almacenamiento persistente de NetApp para contenedores: NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* Kit de herramientas DataOps de NetApp
+
https://github.com/NetApp/netapp-dataops-toolkit["https://github.com/NetApp/netapp-dataops-toolkit"^]

* Almacenamiento persistente de NetApp para contenedores: NetApp Trident
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/["https://netapp.io/persistent-storage-provisioner-for-kubernetes/"^]

* Protopia AI—Inferencia confidencial
+
https://protopia.ai/blog/protopia-ai-takes-on-the-missing-link-in-ai-privacy-confidential-inference/["https://protopia.ai/blog/protopia-ai-takes-on-the-missing-link-in-ai-privacy-confidential-inference/"^]

* Copia y sincronización de NetApp BlueXP
+
https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works["https://docs.netapp.com/us-en/occm/concept_cloud_sync.html#how-cloud-sync-works"^]

* Servidor de inferencia NVIDIA Triton
+
https://developer.nvidia.com/nvidia-triton-inference-server["https://developer.nvidia.com/nvidia-triton-inference-server"^]

* Documentación del servidor de inferencia NVIDIA Triton
+
https://docs.nvidia.com/deeplearning/triton-inference-server/index.html["https://docs.nvidia.com/deeplearning/triton-inference-server/index.html"^]

* FaceBoxes en PyTorch
+
https://github.com/zisianw/FaceBoxes.PyTorch["https://github.com/zisianw/FaceBoxes.PyTorch"^]





== Expresiones de gratitud

* Mark Cates, gerente principal de productos, NetApp
* Sufian Ahmad, ingeniero de marketing técnico, NetApp
* Hadi Esmaeilzadeh, director de tecnología y profesor de Protopia AI

