---
sidebar: sidebar 
permalink: software/ai-conf-protopia-accuracy.html 
keywords: faceboxes, alpha value, accuracy, comparison 
summary: Para esta validación, realizamos una inferencia para un caso de uso de detección de imágenes utilizando un conjunto de imágenes sin procesar.  Luego realizamos la misma tarea de inferencia en el mismo conjunto de imágenes con la ofuscación de Protopia agregada antes de la inferencia.  Repetimos la tarea utilizando diferentes valores de ALPHA para el componente de ofuscación de Protopia. 
---
= Comparación de la precisión de inferencia
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para esta validación, realizamos una inferencia para un caso de uso de detección de imágenes utilizando un conjunto de imágenes sin procesar.  Luego realizamos la misma tarea de inferencia en el mismo conjunto de imágenes con la ofuscación de Protopia agregada antes de la inferencia.  Repetimos la tarea utilizando diferentes valores de ALPHA para el componente de ofuscación de Protopia.  En el contexto de la ofuscación de Protopia, el valor ALPHA representa la cantidad de ofuscación que se aplica, siendo un valor ALPHA más alto el que representa un mayor nivel de ofuscación.  Luego comparamos la precisión de la inferencia en estas diferentes ejecuciones.

Las siguientes dos tablas proporcionan detalles sobre nuestro caso de uso y describen los resultados.

Protopia trabaja directamente con los clientes para determinar el valor ALPHA apropiado para un caso de uso específico.

|===
| Componente | Detalles 


| Modelo | FaceBoxes (PyTorch) - 


| Conjunto de datos | Conjunto de datos FDDB 
|===
|===
| Ofuscación de protopia | ALFA | Exactitud 


| No | N/A | 0,9337148153739079 


| Sí | 0,05 | 0,9028766627325002 


| Sí | 0,1 | 0,9024301009661478 


| Sí | 0,2 | 0,9081836283186224 


| Sí | 0,4 | 0,9073066107482036 


| Sí | 0,6 | 0,8847816568680239 


| Sí | 0,8 | 0,8841195749171925 


| Sí | 0,9 | 0,8455427675252052 


| Sí | 0,95 | 0,8455427675252052 
|===